services:
  - type: web
    name: agape-school-app
    runtime: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: REACT_APP_API_URL
        value: https://misty-roby-haizard-17a53e2a.koyeb.app
      - key: DISABLE_ESLINT_PLUGIN
        value: "true"
      - key: CI
        value: "false"
    healthCheckPath: /health
    autoDeploy: true
