# Cache bust: 20250412224323
[build]
  base = "frontend/school-frontend-app"
  publish = "build"
  command = "npm install --legacy-peer-deps && npm install jsonwebtoken bcryptjs axios --no-save && node scripts/quick-build.js"

[[plugins]]
package = "@netlify/plugin-functions-install-core"

[build.environment]
  NODE_VERSION = "16"
  NPM_FLAGS = "--no-optional"
  NETLIFY_USE_YARN = "false"
  NODE_OPTIONS = "--max-old-space-size=1536"
  DISABLE_ESLINT_PLUGIN = "true"
  ESLINT_NO_DEV_ERRORS = "true"
  GENERATE_SOURCEMAP = "false"
  REACT_APP_API_URL = "/api"
  REACT_APP_BACKEND_URL = "https://misty-roby-haizard-17a53e2a.koyeb.app"
  CI = "true"

# Handle all routes with the SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
