services:
  # Backend API Service
  - type: web
    name: john-vianney-api
    runtime: node
    rootDir: backend
    region: ohio
    plan: free
    buildCommand: npm ci
    startCommand: node scripts/ensureJwtSecret.js && npm start
    healthCheckPath: /api/health
    buildFilter:
      paths:
        - routes/**/*.js
        - models/**/*.js
        - middleware/**/*.js
        - controllers/**/*.js
        - app.js
        - package.json
        - package-lock.json
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: MONGODB_URI
        fromDatabase:
          name: john-vianney-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_REFRESH_SECRET
        generateValue: true
      - key: USE_MOCK_DATA
        value: "false"
      - key: CORS_ALLOWED_ORIGINS
        # Updated to include the correct frontend URL
        value: "https://john-vianney-frontend.onrender.com,http://localhost:3000"

  # Frontend Service (Web Service using custom server.js)
  - type: web
    name: john-vianney-frontend
    runtime: node
    rootDir: frontend/school-frontend-app
    region: ohio
    plan: free
    buildCommand: npm ci --production=false && npm run build:render-direct
    startCommand: node server.js
    healthCheckPath: /health
    buildFilter:
      paths:
        - src/**/*.js
        - src/**/*.jsx
        - src/**/*.css
        - public/**/*
        - package.json
        - package-lock.json
    envVars:
      - key: NODE_ENV
        value: production
      - key: REACT_APP_API_URL
        value: https://john-vianney-api.onrender.com/api
      - key: REACT_APP_USE_MOCK_DATA
        value: "false"
      - key: REACT_APP_TIMEOUT
        value: "60000"

# Database
databases:
  - name: john-vianney-db
    plan: free
    region: ohio
    databaseName: john_vianney
    ipAllowList: []  # only allow internal connections
